train_dataset:
  dataset:
    name: hr_data_loader
    args:
      split_file: ./data/meta_info_ucm_trainhr.txt
      cache: none
  wrapper:
    name: select_scale_sr_warp
    args:
      scales: [2, 2.5, 3, 3.5, 4]
      patch_size: 48
      augment: true
      val_mode: false
      test_mode: false
  batch_size: 4
  num_workers: 4

val_dataset:
  dataset:
    name: pair_data_loader
    args:
      meta_file: ./data/meta_info_UCMx12_testpair.txt
  wrapper:
    name: fixed_scale_pairsr_warp
    args:
      scale: 12
  scale: 12
  batch_size: 4
  num_workers: 4


data_norm:
  img: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: EESCit
  args:
    backbone_spec:
      name: SymSwinLight_backbone
      args:
        img_size: 48
        patch_size: 1
        in_chans: 3
        embed_dim: 256
        depths: [ 1,1,1,1 ]
        num_heads: [ 8,8,8,8 ]
        window_size: [ 4,8,8,4 ]
        permute_ratio: [2,4,4,2]
        mlp_ratio: 2
    head: 8
    qembed_dim: [256, 128, 64, 32]
    kembed_dim: [256, 128, 128, 256]
    vembed_dim: [256, 128, 128, 256]

optimizer:
  name: adam
  args:
    lr: 2.e-4

lr_scheduler:
  name: CosineAnnealingWarmUpLR
  epochs: 2000
  warm_up_epochs: 50
  eta_min: 1.e-8

epoch_max: 2000
epoch_val: 100
epoch_save: 500
